spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: health, info  # Expose only health and info endpoints in production

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true  # Enable Prometheus for metrics collection