spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # Expose only health and info endpoints in production

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true  # Enable Prometheus for metrics collection